import { Attribute } from "@/types/project";

export const PROJECT_ATTRIBUTES: Attribute[] = [
  {
    id: "ordersPerMonth",
    name: "Pedidos/Mês",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "averageTicket",
    name: "Ticket Médio",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "skuCount",
    name: "Quantidade de SKUs",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "newProductsPercentage",
    name: "% Novos Produtos",
    unit: "percentage",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "registeredCustomers",
    name: "Número de Clientes Cadastrados",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "serviceChannels",
    name: "Canais de Atendimento",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "marketplaceChannels",
    name: "Número de Canais no Marketplace",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "customerServiceTime",
    name: "Tempo de Atendimento por Cliente (Min)",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "servicePercentage",
    name: "% Atendimento",
    unit: "percentage",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "returnsPercentage",
    name: "% Devoluções",
    unit: "percentage",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "productAttributes",
    name: "Atributos de Produto",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "institutionalContentUpdate",
    name: "Atualização de Conteúdo Institucional",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "improvementsImplementation",
    name: "Implementação de Melhorias",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "configurationUpdate",
    name: "Atualização de Configuração",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "businessRulesUpdate",
    name: "Atualização de Regras de Negócio",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "promotionalRulesCreation",
    name: "Criação de Regras Promocionais",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "technicalSupport",
    name: "Suporte Técnico",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "ecommerceTraining",
    name: "Treinamento para o Ecommerce",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "serviceConfigUpdate",
    name: "Atualização de Configurações de Atendimento",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "frontendBugFixes",
    name: "Correção de Erros no Front",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "integrationBugFixes",
    name: "Correção de Erros de Integração",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "bugMonitoring",
    name: "Monitoramento de Bugs",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
];
