
import { Attribute } from "@/types/project";

export const PROJECT_ATTRIBUTES: Attribute[] = [
  {
    id: "ORDERS_PER_MONTH",
    name: "Pedidos/Mês",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "AVERAGE_TICKET",
    name: "Ticket Médio",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "SKU_COUNT",
    name: "Quantidade de SKUs",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "NEW_PRODUCTS_PERCENTAGE",
    name: "% Novos Produtos",
    unit: "percentage",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "REGISTERED_CUSTOMERS",
    name: "Número de Clientes Cadastrados",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "SERVICE_CHANNELS",
    name: "Canais de Atendimento",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "MARKETPLACE_CHANNELS",
    name: "Número de Canais no Marketplace",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "CUSTOMER_SERVICE_TIME",
    name: "Tempo de Atendimento por Cliente (Min)",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "SERVICE_PERCENTAGE",
    name: "% Atendimento",
    unit: "percentage",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "RETURNS_PERCENTAGE",
    name: "% Devoluções",
    unit: "percentage",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "PRODUCT_ATTRIBUTES",
    name: "Atributos de Produto",
    unit: "quantity",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "INSTITUTIONAL_CONTENT_UPDATE",
    name: "Atualização de Conteúdo Institucional",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "IMPROVEMENTS_IMPLEMENTATION",
    name: "Implementação de Melhorias",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "CONFIGURATION_UPDATE",
    name: "Atualização de Configuração",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "BUSINESS_RULES_UPDATE",
    name: "Atualização de Regras de Negócio",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "PROMOTIONAL_RULES_CREATION",
    name: "Criação de Regras Promocionais",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "TECHNICAL_SUPPORT",
    name: "Suporte Técnico",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "ECOMMERCE_TRAINING",
    name: "Treinamento para o Ecommerce",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "SERVICE_CONFIG_UPDATE",
    name: "Atualização de Configurações de Atendimento",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "FRONTEND_BUG_FIXES",
    name: "Correção de Erros no Front",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "INTEGRATION_BUG_FIXES",
    name: "Correção de Erros de Integração",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
  {
    id: "BUG_MONITORING",
    name: "Monitoramento de Bugs",
    unit: "hours",
    type: "number",
    defaultValue: "0",
  },
];
