// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktimkjlznjnpptcrgrtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0aW1ramx6bmpucHB0Y3JncnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NzkwNTYsImV4cCI6MjA1NDI1NTA1Nn0.GMClTB9I5UlEPmjSLNWjiqGJMAgSj0cAgXFG8s1MrgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);